### ISSUE TITLE
SecurityPolicy can not delete a rule when this rule index is not last one. 

### ISSUE THREAD

**Issue by timdengyun** [vmware-tanzu/nsx-operator#394]
In certain case, SecurityPolicy can not delete a rule  when this rule index is not last one. 
For example, for the SP below:
```
apiVersion: nsx.vmware.com/v1alpha1
kind: SecurityPolicy
metadata:
  name: sp-app-access222
  namespace: ns-1
spec:
  priority: 0
  appliedTo:
    - podSelector:
        matchLabels:
          role: db
  rules:
    - direction: in ----->>rule1
      action: allow
      sources:
        - podSelector:
            matchLabels:
              app: coffee
      ports:
        - protocol: TCP
          port: 6001

    - direction: in ----->>rule2
      action: allow
      sources:
        - vmSelector:
            matchLabels:
              app: coco
      ports:
        - protocol: TCP
          port: 8282

    - direction: out. ----->>rule3
      action: allow
      destinations:
        - namespaceSelector:
            matchLabels:
              ns-name: ns-2
          vmSelector:
            matchLabels:
              app: web
      ports:
        - protocol: TCP
          port: 3306
```
When user tries to delete the second rule2, it will fail. The error is showing the source group in the rule 2 is being used and can not be deleted. 
```
    - direction: in
      action: allow
      sources:
        - vmSelector:
            matchLabels:
              app: coco
      ports:
        - protocol: TCP
          port: 8282
```

This issue is caused by the original rule2 ID: sp_spUID_1_0_0 will be regenerated by the original rule3, since we don't use the unique ID for the each rule generated.
