### ISSUE TITLE
DHCP subnetport has ipAddress "/26"

### ISSUE THREAD

**Issue by heypnus** [vmware-tanzu/nsx-operator#559]
```
status:
  attachment:
    id: 39383535-6338-4132-ad38-6537372d3432
  conditions:
  - lastTransitionTime: "2024-05-01T21:19:17Z"
    message: NSX subnet port has been successfully created/updated
    reason: NSX API returned 200 response code for PATCH
    status: "True"
    type: Ready
  networkInterfaceConfig:
    ipAddresses:
    - gateway: 172.26.1.1
      ipAddress: /26     <----------------------------
    logicalSwitchUUID: 7c5f3494-545e-4162-bf56-b11e1260ae66
```
The ipAddress looks not regular. If we follow the T1 networking implementation, the ipAddress should be null, but that has a side effect that the VM operator cannot calculate the netmask from ipAddress. According to the discussion, the side effect is acceptable from VM operator side. Let's use the issue to track the fix.
